kaggle_train_events: train_events.csv
kaggle_train_series: train_series.parquet

postprocessed_target: train_postprocessed_target.csv
target_data: train_target.csv
mask_data: train_mask.csv
base_data: train_base_data.csv
train_data: train_data.npy

mode: train
